### PR TITLE
updated offsets

### PR DESCRIPTION
**Pull request by dankor33**
here you go skids like me

### CODE REVIEW

**Comment by Riz-ve** [comment]
I have already updated the offsets in the release but not the commit because some people are using my source to sell it to others n stuff. You are also missing some offsets

**Comment by playvoras** [comment]
> Reference

thats really good way!

**Comment by floppa1511** [comment]
how do u dump offsets gang

**Comment by markitos4** [comment]
how yall update offsets omg i have tried dumpers but it gives me a broken roblox executable that when i try to decompile with ida pro it just doesnt loads nothing. And using cheat engine on roblox studio actually gives me some of the offsets but i dont know how to get all of them which are the most important  :(

**Pull request closed without merging**
